WAV snd_campana "sfx/snd_campana.wav" XGM2
WAV snd_bomba "sfx/snd_bomba.wav" XGM2
WAV snd_canon "sfx/snd_canon.wav" XGM2
WAV snd_regalo_recogido "sfx/snd_regalo_recogido.wav" XGM2
WAV snd_obstaculo_golpe "sfx/snd_obstaculo_golpe.wav" XGM2
WAV snd_elfo_robando "sfx/snd_elfo_robando.wav" XGM2
WAV snd_regalo_disparado1 "sfx/snd_regalo_disparado1.wav" XGM2
WAV snd_regalo_disparado2 "sfx/snd_regalo_disparado2.wav" XGM2
WAV snd_regalo_disparado3 "sfx/snd_regalo_disparado3.wav" XGM2
WAV snd_elfo_choque "sfx/snd_elfo_choque.wav" XGM2
WAV snd_santa_hohoho "sfx/snd_santa_hohoho.wav" XGM2
WAV snd_regalo_desaparece "sfx/snd_regalo_desaparece.wav" XGM2
WAV snd_elfo_volador_robando_1 "sfx/snd_elfo_volador_robando_1.wav" XGM2
WAV snd_elfo_volador_robando_2 "sfx/snd_elfo_volador_robando_2.wav" XGM2
WAV snd_regalo_quemado "sfx/snd_regalo_quemado.wav" XGM2
WAV snd_sleigh_chase "sfx/snd_sleighchase.wav" XGM2
WAV snd_victoria "sfx/snd_victoria.wav" XGM2
