XGM2 music_geesebumps "Geesebumps/Goosebumps_intro.vgm" 
XGM2 musica_MerryGentelmen "music/MerryGentelmen.vgm"
XGM2 musica_Rudolph "music/Rudolph.vgm"
XGM2 musica_SleighRide "music/SleighRide.vgm"
XGM2 musica_Fanfarria "music/Fanfarria.vgm"